config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  devise_for :users, path_names: {
                 sign_in: 'login',
                 sign_out: 'logout',
                   }

  get 'about/index', to: 'about#index', as: :about

  get 'photos/index', to: 'photos#index', as: :photos
  get 'photos/show', to: 'photos#show', as: :album

  get 'perso/index', to: 'perso#index', as: :perso_projects
  get 'perso/show', to: 'perso#show', as: :perso_project

  get 'resume/index', to: 'resume#index', as: :resume

  get 'book/index', to: 'book#index', as: :book

  get 'locations/show', to: 'locations#show', as: :location

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  get 'projects/show'

  namespace :admin do
    get '', to: 'about#show', as: '/'

    match '/about/:id/edit' => 'about#update', :via => :post
    resources :about

    resources :resume
    post 'resume/resume_upload' => 'resume#resume_upload', :as => :resume_upload

    resources :cursus
    get 'cursus/:id/delete' => 'cursus#delete', :as => :cursu_delete
    get 'cursus/:id/destroy' => 'cursus#destroy', :as => :cursu_destroy

    resources :experience
    get 'experience/:id/delete' => 'experience#delete', :as => :experience_delete
    get 'experience/:id/destroy' => 'experience#destroy', :as => :experience_destroy

    resources :skills
    get 'skills/:id/delete' => 'skills#delete', :as => :skill_delete
    get 'skills/:id/destroy' => 'skills#destroy', :as => :skill_destroy

    resources :locations
    get 'locations/:id/delete' => 'locations#delete', :as => :location_delete
    get 'locations/:id/destroy' => 'locations#destroy', :as => :location_destroy

    resources :projects
    get 'projects/:id/delete' => 'projects#delete', :as => :project_delete
    get 'projects/:id/destroy' => 'projects#destroy', :as => :project_destroy

    resources :perso_projects
    get 'perso_projects/:id/delete' => 'perso_projects#delete', :as => :perso_project_delete
    get 'perso_projects/:id/destroy' => 'perso_projects#destroy', :as => :perso_project_destroy

    resources :photo
    get 'photo/:id/delete' => 'photo#delete', :as => :photo_delete
    get 'photo/:id/destroy' => 'photo#destroy', :as => :photo_destroy

    resources :albums
    get 'albums/:id/delete' => 'albums#delete', :as => :album_delete
    get 'albums/:id/destroy' => 'albums#destroy', :as => :album_destroy

    get 'contact/index' => 'contact#index', :as => :contact
    get 'contact/update' => 'contact#update', :as => :update_contact

  end

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :albums, :dependent => :destroy

  validates :name_fr, presence: true, length: { maximum: 300, too_long: "%{count} charactères autorisés"}
  validates :name_en, presence: true, length: { maximum: 300, too_long: "%{count} charactères autorisés"}
  validates :description_fr, length: { maximum: 3000, too_long: "%{count} charactères autorisés"}
  validates :description_en, length: { maximum: 3000, too_long: "%{count} charactères autorisés"}

  #main image upload definition for paperclip
  has_attached_file :main_image,
                    :styles => {:medium => "300x300", :thumb => "100x100", :grey => "300x300", :large => "800x800"},
                    :convert_options => {:grey => "-colorspace Gray"},
                    :path => ":rails_root/public/images/locations/:id/:style_:basename.:extension",
                    :url => ":class/:id/:style_:basename.:extension",
                    :default_url => "/images/errors/no_pic_available.jpg"
  validates_attachment_content_type :main_image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < ApplicationController

  layout 'admin'
  before_action :authenticate_user!

  def index
    if I18n.locale == "fr"
      @locations = Location.all.order(name_fr: :asc)
    else
      @locations = Location.all.order(name_en: :asc)
    end
  end

  def show
    @location = Location.find(params[:id])
    @projects = @location.albums
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      flash[:notice] = "Le lieu à été créé"
      redirect_to(admin_location_path(:id => @location.id))
    else
      render('new')
    end
  end

  def edit
    @location = Location.find(params[:id])
    @projects = @location.albums
  end

  def update
    @location = Location.find(params[:id])
    if @location.update_attributes(location_params)
      flash[:notice] = "Le lieu est mis à jour"
      redirect_to(admin_location_path(:id => @location.id))
    else
      @projects = @location.albums
      render('edit')
    end
  end

  def delete
    @location = Location.find(params[:id])
  end

  def destroy
    @location = Location.find(params[:id]).destroy
    flash[:notice] = "Le lieu à été supprimé"
    redirect_to(:controller => 'locations', :action => 'index')
  end


  private

  def location_params
    params.require(:location).permit(:name_fr, :name_en, :main_image, :description_fr, :description_en)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def show
    @location = Location.find(params[:id])
    @projects = @location.albums

    if I18n.locale == :fr
      @page_title = @location.name_fr
      @description = @location.description_fr
    else
      @page_title = @location.name_en
      @description = @location.description_en
    end
  end
end

app/helpers/admin/locations_helper.rb
module Admin::LocationsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/admin/locations/create.html.erb
<h1>Admin::Locations#create</h1>
<p>Find me in app/views/admin/locations/create.html.erb</p>

app/views/admin/locations/delete.html.erb
<h1><%=t('admin.locations.delete.title')%></h1>

<%= link_to t('admin.buttons.delete'), admin_location_destroy_path(:id => @location.id), :class => 'button radius tiny alert' %>
<%= link_to t('admin.buttons.edit'), edit_admin_location_path(@location), :class => 'button radius tiny secondary' %>
<%= link_to t('admin.buttons.back'), admin_locations_path, :class => 'button radius tiny' %>


<div class="row">

  <div class="infos small-9 columns">
    <ul class="tabs" data-tab>
      <li class="tab-title active"><a href="#panel1"><%=t('admin.language.fr')%></a></li>
      <li class="tab-title"><a href="#panel2"><%=t('admin.language.en')%></a></li>
    </ul>

    <div class="tabs-content">

      <div class="content contained active" id="panel1">

        <table>
          <tr>
            <td class="cell1"><strong><%=t('activerecord.attributes.locations.name_fr')%>:</strong></td>
            <td class="cell2"><%= @location.name_fr %></td>
          </tr>
          <tr>
            <td class="cell1"><strong><%=t('activerecord.attributes.locations.description_fr')%>:</strong></td>
            <td class="cell2"><%= @location.description_fr %></td>
          </tr>
        </table>

      </div>

      <div class="content contained" id="panel2">

        <table>
          <tr>
            <td class="cell1"><strong><%=t('activerecord.attributes.locations.name_en')%>:</strong></td>
            <td class="cell2"><%= @location.name_en %></td>
          </tr>
          <tr>
            <td class="cell1"><strong><%=t('activerecord.attributes.locations.description_en')%>:</strong></td>
            <td class="cell2"><%= @location.description_en %></td>
          </tr>
        </table>

      </div>

    </div>
  </div>

  <div class="info-image small-3 columns">
    <%= image_tag @location.main_image(:medium) %>
  </div>

</div>

<%= link_to t('admin.buttons.delete'), admin_location_destroy_path(:id => @location.id), :class => 'button radius tiny alert' %>
<%= link_to t('admin.buttons.edit'), edit_admin_location_path(@location), :class => 'button radius tiny secondary' %>
<%= link_to t('admin.buttons.back'), admin_locations_path, :class => 'button radius tiny' %>

app/views/admin/locations/destroy.html.erb
<h1>Admin::Locations#destroy</h1>
<p>Find me in app/views/admin/locations/destroy.html.erb</p>

app/views/admin/locations/edit.html.erb
<h1><%=t('admin.locations.edit.title')%></h1>

<% if @location.errors.any? %>
    <div class="error_explanation small-8 small-centered columns">
      <h6><%= @location.errors.count %> <%=t('admin.forms.message.error')%> :</h6>

      <ul>
        <% @location.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_for(@location, url: admin_location_path) do |f| %>


    <div class="row">

      <div class="infos small-9 columns">
        <ul class="tabs" data-tab>
          <li class="tab-title active"><a href="#panel1"><%=t('admin.language.fr')%></a></li>
          <li class="tab-title"><a href="#panel2"><%=t('admin.language.en')%></a></li>
        </ul>

        <div class="tabs-content">

          <div class="content contained active" id="panel1">

            <table>
              <tr><td class="cell1"><%= f.label t('activerecord.attributes.locations.name_fr')%></td>
                <td class="cell2"><%= f.text_field :name_fr %></td>
              </tr>
              <tr>
                <td class="cell1"><%= f.label t('activerecord.attributes.locations.description_fr')%></td>
                <td class="cell2"><%= f.text_area :description_fr, :class => 'ckeditor' %></td>
              </tr>
            </table>

          </div>

          <div class="content contained" id="panel2">

            <table>
              <tr>
                <td class="cell1"><%= f.label t('activerecord.attributes.locations.name_en')%></td>
                <td class="cell2"><%= f.text_field :name_en%></td>
              </tr>
              <tr>
                <td class="cell1"><%= f.label t('activerecord.attributes.locations.description_en')%></td>
                <td class="cell2"><%= f.text_area :description_en, :class => 'ckeditor' %></td>
              </tr>
            </table>

          </div>

        </div>
      </div>

      <div class="info-image small-3 columns">
        <%= f.label t('activerecord.attributes.locations.main_image')%>
        <%= f.file_field :main_image %>
      </div>

    </div>

    <div class="submit">
      <%= f.submit t('admin.buttons.save'), :class => 'button radius tiny info' %>
    </div>
<% end %>


<div class="projects">
  <h1><%=t('admin.projects.index.title')%></h1>

  <%= link_to t('admin.buttons.new'), new_admin_project_path(:location_id => @location.id), :class => 'button radius tiny success' %>
  <div class="table-container">
      <table>
        <thead>
        <tr>
          <th><%=t('activerecord.attributes.albums.name_fr')%></th>
          <th><%=t('activerecord.attributes.albums.name_en')%></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
        </thead>

        <tbody>
        <% @projects.each do |project| %>
            <tr>
              <td><%= project.name_fr %></td>
              <td><%= project.name_en %></td>
              <td><%= link_to t('admin.buttons.show'), admin_project_path(project), :class => 'button radius tiny info' %></td>
              <td><%= link_to t('admin.buttons.edit'), edit_admin_project_path(project), :class => 'button radius tiny secondary' %></td>
              <td><%= link_to t('admin.buttons.delete'), admin_project_delete_path(project), :class => 'button radius tiny alert' %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
</div>

app/views/admin/locations/index.html.erb
<div class="table-container">
  <h1><%=t('admin.locations.index.title')%></h1>
  <%= link_to t('admin.buttons.new'), new_admin_location_path, :class => 'button radius tiny success' %>
  <table>
    <thead>
    <tr>
      <th><%=t('activerecord.attributes.locations.name_fr')%></th>
      <th><%=t('activerecord.attributes.locations.name_en')%></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% @locations.each do |location| %>
        <tr>
          <td><%= location.name_fr %></td>
          <td><%= location.name_en %></td>
          <td><%= link_to t('admin.buttons.show'), admin_location_path(location), :class => 'button radius tiny info' %></td>
          <td><%= link_to t('admin.buttons.edit'), edit_admin_location_path(location), :class => 'button radius tiny secondary' %></td>
          <td><%= link_to t('admin.buttons.delete'), admin_location_delete_path(location), :class => 'button radius tiny alert' %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/admin/locations/new.html.erb
<h1><%=t('admin.locations.new.title')%></h1>


<% if @location.errors.any? %>
    <div class="error_explanation small-8 small-centered columns">
      <h6><%= @location.errors.count %> <%=t('admin.forms.message.error')%> :</h6>

      <ul>
        <% @location.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_for(@location, url: admin_locations_path) do |f| %>

    <div class="row">

      <div class="infos small-9 columns">
        <ul class="tabs" data-tab>
          <li class="tab-title active"><a href="#panel1"><%=t('admin.language.fr')%></a></li>
          <li class="tab-title"><a href="#panel2"><%=t('admin.language.en')%></a></li>
        </ul>

        <div class="tabs-content">

          <div class="content contained active" id="panel1">

            <table>
              <tr><td class="cell1"><%= f.label t('activerecord.attributes.locations.name_fr')%></td>
                <td class="cell2"><%= f.text_field :name_fr %></td>
              </tr>
              <tr>
                <td class="cell1"><%= f.label t('activerecord.attributes.locations.description_fr')%></td>
                <td class="cell2"><%= f.text_area :description_fr, :class => 'ckeditor' %></td>
              </tr>
            </table>

          </div>

          <div class="content contained" id="panel2">

            <table>
              <tr>
                <td class="cell1"><%= f.label t('activerecord.attributes.locations.name_en')%></td>
                <td class="cell2"><%= f.text_field :name_en%></td>
              </tr>
              <tr>
                <td class="cell1"><%= f.label t('activerecord.attributes.locations.description_en')%></td>
                <td class="cell2"><%= f.text_area :description_en, :class => 'ckeditor' %></td>
              </tr>
            </table>

          </div>

        </div>
      </div>

      <div class="info-image small-3 columns">
        <%= f.label t('activerecord.attributes.locations.main_image')%>
        <%= f.file_field :main_image %>
      </div>

    </div>

    <div class="submit">
      <%= f.submit t('admin.buttons.save'), :class => 'button radius tiny info' %>
    </div>
<% end %>

app/views/admin/locations/show.html.erb
<h1><%=t('admin.locations.show.title')%></h1>

<%= link_to t('admin.buttons.edit'), edit_admin_location_path(@location), :class => 'button radius tiny secondary' %>
<%= link_to t('admin.buttons.back'), admin_locations_path, :class => 'button radius tiny ' %>


<div class="row">

  <div class="infos small-9 columns">

    <ul class="tabs" data-tab>
      <li class="tab-title active"><a href="#panel1"><%=t('admin.language.fr')%></a></li>
      <li class="tab-title"><a href="#panel2"><%=t('admin.language.en')%></a></li>
    </ul>

    <div class="tabs-content">

      <div class="content contained active" id="panel1">

        <table>
          <tr>
            <td class="cell1"><strong><%=t('activerecord.attributes.locations.name_fr')%>:</strong></td>
            <td class="cell2"><%= @location.name_fr.html_safe %></td>
          </tr>
          <tr>
            <td class="cell1"><strong><%=t('activerecord.attributes.locations.description_fr')%>:</strong></td>
            <td class="cell2"><%= @location.description_fr.html_safe %></td>
          </tr>
        </table>

      </div>

      <div class="content contained" id="panel2">

        <table>
          <tr>
            <td class="cell1"><strong><%=t('activerecord.attributes.locations.name_en')%>:</strong></td>
            <td class="cell2"><%= @location.name_en.html_safe %></td>
          </tr>
          <tr>
            <td class="cell1"><strong><%=t('activerecord.attributes.locations.description_en')%>:</strong></td>
            <td class="cell2"><%= @location.description_en.html_safe %></td>
          </tr>
        </table>

      </div>

    </div>
  </div>

  <div class="info-image small-3 columns">
    <%= image_tag @location.main_image(:medium) %>
  </div>

</div>



<%= link_to t('admin.buttons.edit'), edit_admin_location_path(@location), :class => 'button radius tiny secondary' %>
<%= link_to t('admin.buttons.back'), admin_locations_path, :class => 'button radius tiny ' %>

<div class="projects">
  <h1><%=t('admin.projects.index.title')%></h1>

  <%= link_to t('admin.buttons.new'), new_admin_project_path(:location_id => @location.id), :class => 'button radius tiny success' %>
    <div class="table-container">
      <table>
        <thead>
        <tr>
          <th><%=t('activerecord.attributes.albums.name_fr')%></th>
          <th><%=t('activerecord.attributes.albums.name_en')%></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
        </thead>

        <tbody>
        <% @projects.each do |project| %>
            <tr>
              <td><%= project.name_fr %></td>
              <td><%= project.name_en %></td>
              <td><%= link_to t('admin.buttons.show'), admin_project_path(project), :class => 'button radius tiny info' %></td>
              <td><%= link_to t('admin.buttons.edit'), edit_admin_project_path(project), :class => 'button radius tiny secondary' %></td>
              <td><%= link_to t('admin.buttons.delete'), admin_project_delete_path(project), :class => 'button radius tiny alert' %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
</div>

app/views/admin/locations/update.html.erb
<h1>Admin::Locations#update</h1>
<p>Find me in app/views/admin/locations/update.html.erb</p>