config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  devise_for :users, path_names: {
                 sign_in: 'login',
                 sign_out: 'logout',
                   }

  get 'about/index', to: 'about#index', as: :about

  get 'photos/index', to: 'photos#index', as: :photos
  get 'photos/show', to: 'photos#show', as: :album

  get 'perso/index', to: 'perso#index', as: :perso_projects
  get 'perso/show', to: 'perso#show', as: :perso_project

  get 'resume/index', to: 'resume#index', as: :resume

  get 'book/index', to: 'book#index', as: :book

  get 'locations/show', to: 'locations#show', as: :location

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  get 'projects/show'

  namespace :admin do
    get '', to: 'about#show', as: '/'

    match '/about/:id/edit' => 'about#update', :via => :post
    resources :about

    resources :resume
    post 'resume/resume_upload' => 'resume#resume_upload', :as => :resume_upload

    resources :cursus
    get 'cursus/:id/delete' => 'cursus#delete', :as => :cursu_delete
    get 'cursus/:id/destroy' => 'cursus#destroy', :as => :cursu_destroy

    resources :experience
    get 'experience/:id/delete' => 'experience#delete', :as => :experience_delete
    get 'experience/:id/destroy' => 'experience#destroy', :as => :experience_destroy

    resources :skills
    get 'skills/:id/delete' => 'skills#delete', :as => :skill_delete
    get 'skills/:id/destroy' => 'skills#destroy', :as => :skill_destroy

    resources :locations
    get 'locations/:id/delete' => 'locations#delete', :as => :location_delete
    get 'locations/:id/destroy' => 'locations#destroy', :as => :location_destroy

    resources :projects
    get 'projects/:id/delete' => 'projects#delete', :as => :project_delete
    get 'projects/:id/destroy' => 'projects#destroy', :as => :project_destroy

    resources :perso_projects
    get 'perso_projects/:id/delete' => 'perso_projects#delete', :as => :perso_project_delete
    get 'perso_projects/:id/destroy' => 'perso_projects#destroy', :as => :perso_project_destroy

    resources :photo
    get 'photo/:id/delete' => 'photo#delete', :as => :photo_delete
    get 'photo/:id/destroy' => 'photo#destroy', :as => :photo_destroy

    resources :albums
    get 'albums/:id/delete' => 'albums#delete', :as => :album_delete
    get 'albums/:id/destroy' => 'albums#destroy', :as => :album_destroy

    get 'contact/index' => 'contact#index', :as => :contact
    get 'contact/update' => 'contact#update', :as => :update_contact

  end

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

end

app/controllers/admin/experience_controller.rb
class Admin::ExperienceController < ApplicationController

  layout "admin"
  before_action :authenticate_user!

  def index
      @experiences = ProfessionalExperience.all.order(date: :asc)
  end

  def show
    @experience = ProfessionalExperience.find(params[:id])
  end

  def new
    @experience = ProfessionalExperience.new
  end

  def create
    @experience = ProfessionalExperience.new(professional_experience_params)
    if @experience.save
      flash[:notice] = "L'expérience à été créé"
      redirect_to(admin_experience_path(:id => @experience.id))
    else
      render('new')
    end
  end

  def edit
    @experience = ProfessionalExperience.find(params[:id])
  end

  def update
    @experience = ProfessionalExperience.find(params[:id])
    if @experience.update_attributes(professional_experience_params)
      flash[:notice] = "L'expérience est mise à jour"
      redirect_to(admin_experience_path(:id => @experience.id))
    else
      render('edit')
    end
  end

  def delete
    @experience = ProfessionalExperience.find(params[:id])
  end

  def destroy
    @experience = ProfessionalExperience.find(params[:id]).destroy
    flash[:notice] = "L'expérience à été supprimée"
    redirect_to(:controller => 'resume', :action => 'index')
  end

  private

  def professional_experience_params
    params.require(:professional_experience).permit(:start_date, :end_date, :company, :location_fr, :location_en, :description_fr, :description_en)
  end
end

app/helpers/admin/experience_helper.rb
module Admin::ExperienceHelper
end

app/views/admin/experience/create.html.erb
<h1>Admin::Experience#create</h1>
<p>Find me in app/views/admin/experience/create.html.erb</p>

app/views/admin/experience/delete.html.erb
<h1><%=t('admin.experience.delete.title')%></h1>


<%= link_to t('admin.buttons.delete'), admin_experience_destroy_path(:id => @experience.id), :class => 'button radius tiny alert' %>
<%= link_to t('admin.buttons.edit'), edit_admin_experience_path(@experience), :class => 'button radius tiny secondary' %>
<%= link_to t('admin.buttons.back'), admin_resume_index_path, :class => 'button radius tiny'  %>

<p>
  <strong><%=t('activerecord.attributes.professional_experiences.date')%>:</strong>
  <%= @experience.date %>
</p>

<p>
  <strong><%=t('activerecord.attributes.professional_experiences.company')%>:</strong>
  <%= @experience.company.html_safe %>
</p>

<ul class="tabs" data-tab>
  <li class="tab-title active"><a href="#panel1"><%=t('admin.language.fr')%></a></li>
  <li class="tab-title"><a href="#panel2"><%=t('admin.language.en')%></a></li>
</ul>

<div class="tabs-content">

  <div class="content contained active" id="panel1">

    <table>
      <tr>
        <td class="cell1"><strong><%=t('activerecord.attributes.professional_experiences.location_fr')%>:</strong></td>
        <td class="cell2"><%= @experience.location_fr.html_safe %></td>
      </tr>
      <tr>
        <td colspan="2">
          <div class="separator small-12 columns">
            <div class="mask-small"></div>
          </div>
        </td>
      </tr>
      <tr>
        <td class="cell1"><strong><%=t('activerecord.attributes.professional_experiences.description_fr')%>:</strong></td>
        <td class="cell2"><%= @experience.description_fr.html_safe %></td>
      </tr>
    </table>

  </div>

  <div class="content contained" id="panel2">

    <table>
      <tr>
        <td class="cell1"><strong><%=t('activerecord.attributes.professional_experiences.location_en')%>:</strong></td>
        <td class="cell2"><%= @experience.location_en.html_safe %></td>
      </tr>
      <tr>
        <td colspan="2">
          <div class="separator small-12 columns">
            <div class="mask-small"></div>
          </div>
        </td>
      </tr>
      <tr>
        <td class="cell1"><strong><%=t('activerecord.attributes.professional_experiences.description_en')%>:</strong></td>
        <td class="cell2"><%= @experience.description_en.html_safe %></td>
      </tr>
    </table>

  </div>



  <%= link_to t('admin.buttons.delete'), admin_experience_destroy_path(:id => @experience.id), :class => 'button radius tiny alert' %>
<%= link_to t('admin.buttons.edit'), edit_admin_experience_path(@experience), :class => 'button radius tiny secondary' %>
<%= link_to t('admin.buttons.back'), admin_resume_index_path, :class => 'button radius tiny'  %>

app/views/admin/experience/destroy.html.erb
<h1>Admin::Experience#destroy</h1>
<p>Find me in app/views/admin/experience/destroy.html.erb</p>

app/views/admin/experience/edit.html.erb
<h1><%=t('admin.experience.edit.title')%></h1>

<% if @experience.errors.any? %>
    <div class="error_explanation small-8 small-centered columns">
      <h6><%= @experience.errors.count %> <%=t('admin.forms.message.error')%> :</h6>

      <ul>
        <% @experience.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_for(@experience, url: admin_experience_path) do |f| %>

    <div class="date">
      <%= f.label t('activerecord.attributes.professional_experiences.startdate')%>
      <%= f.text_field :start_date, :class => 'datepicker' %>
    </div>

    <div class="date">
      <%= f.label t('activerecord.attributes.professional_experiences.enddate')%>
      <%= f.text_field :end_date, :class => 'datepicker' %>
    </div>

    <div class="company">
      <%= f.label t('activerecord.attributes.professional_experiences.company')%>
      <%= f.text_field :company %>
    </div>

    <ul class="tabs" data-tab>
      <li class="tab-title active"><a href="#panel1"><%=t('admin.language.fr')%></a></li>
      <li class="tab-title"><a href="#panel2"><%=t('admin.language.en')%></a></li>
    </ul>

    <div class="tabs-content">

      <div class="content contained active" id="panel1">

        <table>
          <tr>
            <td class="cell1"><%= f.label t('activerecord.attributes.professional_experiences.location_fr')%></td>
            <td class="cell2"><%= f.text_field :location_fr %></td>
          </tr>
          <tr>
            <td colspan="2">
              <div class="separator small-12 columns">
                <div class="mask-small"></div>
              </div>
            </td>
          </tr>
          <tr>
            <td class="cell1"><%= f.label t('activerecord.attributes.professional_experiences.description_fr')%></td>
            <td class="cell2"><%= f.text_area :description_fr, :class => 'ckeditor' %></td>
          </tr>
        </table>

      </div>

      <div class="content contained" id="panel2">

        <table>
          <tr>
            <td class="cell1"><%= f.label t('activerecord.attributes.professional_experiences.location_en')%></td>
            <td class="cell2"><%= f.text_field :location_en%></td>
          </tr>
          <tr>
            <td colspan="2">
              <div class="separator small-12 columns">
                <div class="mask-small"></div>
              </div>
            </td>
          </tr>
          <tr>
            <td class="cell1"><%= f.label t('activerecord.attributes.professional_experiences.description_en')%></td>
            <td class="cell2"><%= f.text_area :description_en, :class => 'ckeditor' %></td>
          </tr>
        </table>

      </div>

    </div>

    <div class="submit">
      <%= f.submit t('admin.buttons.save'), :class => 'button radius tiny info' %>
    </div>
<% end %>

app/views/admin/experience/index.html.erb
<h1>Admin::Experience#index</h1>
<p>Find me in app/views/admin/experience/index.html.erb</p>

app/views/admin/experience/new.html.erb
<h1><%=t('admin.experience.new.title')%></h1>

<% if @experience.errors.any? %>
    <div class="error_explanation small-8 small-centered columns">
      <h6><%= @experience.errors.count %> <%=t('admin.forms.message.error')%> :</h6>

      <ul>
        <% @experience.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_for(@experience, url: admin_experience_index_path, :html => { :mulipart => true}) do |f| %>

    <div class="date">
      <%= f.label t('activerecord.attributes.professional_experiences.startdate')%>
      <%= f.text_field :start_date, :class => 'datepicker' %>
    </div>

    <div class="date">
      <%= f.label t('activerecord.attributes.professional_experiences.enddate')%>
      <%= f.text_field :end_date, :class => 'datepicker' %>
    </div>

    <div class="company">
      <%= f.label t('activerecord.attributes.professional_experiences.company')%>
      <%= f.text_field :company %>
    </div>

    <ul class="tabs" data-tab>
      <li class="tab-title active"><a href="#panel1"><%=t('admin.language.fr')%></a></li>
      <li class="tab-title"><a href="#panel2"><%=t('admin.language.en')%></a></li>
    </ul>

    <div class="tabs-content">

      <div class="content contained active" id="panel1">

        <table>
          <tr>
            <td class="cell1"><%= f.label t('activerecord.attributes.professional_experiences.location_fr')%></td>
            <td class="cell2"><%= f.text_field :location_fr %></td>
          </tr>
          <tr>
            <td colspan="2">
              <div class="separator small-12 columns">
                <div class="mask-small"></div>
              </div>
            </td>
          </tr>
          <tr>
            <td class="cell1"><%= f.label t('activerecord.attributes.professional_experiences.description_fr')%></td>
            <td class="cell2"><%= f.text_area :description_fr, :class => 'ckeditor' %></td>
          </tr>
        </table>

      </div>

      <div class="content contained" id="panel2">

        <table>
          <tr>
            <td class="cell1"><%= f.label t('activerecord.attributes.professional_experiences.location_en')%></td>
            <td class="cell2"><%= f.text_field :location_en%></td>
          </tr>
          <tr>
            <td colspan="2">
              <div class="separator small-12 columns">
                <div class="mask-small"></div>
              </div>
            </td>
          </tr>
          <tr>
            <td class="cell1"><%= f.label t('activerecord.attributes.professional_experiences.description_en')%></td>
            <td class="cell2"><%= f.text_area :description_en, :class => 'ckeditor' %></td>
          </tr>
        </table>

      </div>

    </div>

    <div class="submit">
      <%= f.submit t('admin.buttons.save'), :class => 'button radius tiny info' %>
    </div>
<% end %>

app/views/admin/experience/show.html.erb
<h1><%=t('admin.experience.show.title')%></h1>

<%= link_to t('admin.buttons.edit'), edit_admin_experience_path(@experience), :class => 'button radius tiny secondary' %>
<%= link_to t('admin.buttons.back'), admin_resume_index_path, :class => 'button radius tiny ' %>

<p>
  <strong><%=t('activerecord.attributes.professional_experiences.startdate')%>:</strong>
  <%= @experience.start_date %>
</p>

<p>
  <strong><%=t('activerecord.attributes.professional_experiences.enddate')%>:</strong>
  <%= @experience.end_date %>
</p>

<p>
  <strong><%=t('activerecord.attributes.professional_experiences.company')%>:</strong>
  <%= @experience.company.html_safe %>
</p>

<ul class="tabs" data-tab>
  <li class="tab-title active"><a href="#panel1"><%=t('admin.language.fr')%></a></li>
  <li class="tab-title"><a href="#panel2"><%=t('admin.language.en')%></a></li>
</ul>

<div class="tabs-content">

  <div class="content contained active" id="panel1">

    <table>
      <tr>
        <td class="cell1"><strong><%=t('activerecord.attributes.professional_experiences.location_fr')%>:</strong></td>
        <td class="cell2"><%= @experience.location_fr.html_safe %></td>
      </tr>
      <tr>
        <td colspan="2">
          <div class="separator small-12 columns">
            <div class="mask-small"></div>
          </div>
        </td>
      </tr>
      <tr>
        <td class="cell1"><strong><%=t('activerecord.attributes.professional_experiences.description_fr')%>:</strong></td>
        <td class="cell2"><%= @experience.description_fr.html_safe %></td>
      </tr>
    </table>

  </div>

  <div class="content contained" id="panel2">

    <table>
      <tr>
        <td class="cell1"><strong><%=t('activerecord.attributes.professional_experiences.location_en')%>:</strong></td>
        <td class="cell2"><%= @experience.location_en.html_safe %></td>
      </tr>
      <tr>
        <td colspan="2">
          <div class="separator small-12 columns">
            <div class="mask-small"></div>
          </div>
        </td>
      </tr>
      <tr>
        <td class="cell1"><strong><%=t('activerecord.attributes.professional_experiences.description_en')%>:</strong></td>
        <td class="cell2"><%= @experience.description_en.html_safe %></td>
      </tr>
    </table>

  </div>

</div>

<%= link_to t('admin.buttons.edit'), edit_admin_experience_path(@experience), :class => 'button radius tiny secondary' %>
<%= link_to t('admin.buttons.back'), admin_resume_index_path, :class => 'button radius tiny ' %>

app/views/admin/experience/update.html.erb
<h1>Admin::Experience#update</h1>
<p>Find me in app/views/admin/experience/update.html.erb</p>