config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  devise_for :users, path_names: {
                 sign_in: 'login',
                 sign_out: 'logout',
                   }

  get 'about/index', to: 'about#index', as: :about

  get 'photos/index', to: 'photos#index', as: :photos
  get 'photos/show', to: 'photos#show', as: :album

  get 'perso/index', to: 'perso#index', as: :perso_projects
  get 'perso/show', to: 'perso#show', as: :perso_project

  get 'resume/index', to: 'resume#index', as: :resume

  get 'book/index', to: 'book#index', as: :book

  get 'locations/show', to: 'locations#show', as: :location

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  get 'projects/show'

  namespace :admin do
    get '', to: 'about#show', as: '/'

    match '/about/:id/edit' => 'about#update', :via => :post
    resources :about

    resources :resume
    post 'resume/resume_upload' => 'resume#resume_upload', :as => :resume_upload

    resources :cursus
    get 'cursus/:id/delete' => 'cursus#delete', :as => :cursu_delete
    get 'cursus/:id/destroy' => 'cursus#destroy', :as => :cursu_destroy

    resources :experience
    get 'experience/:id/delete' => 'experience#delete', :as => :experience_delete
    get 'experience/:id/destroy' => 'experience#destroy', :as => :experience_destroy

    resources :skills
    get 'skills/:id/delete' => 'skills#delete', :as => :skill_delete
    get 'skills/:id/destroy' => 'skills#destroy', :as => :skill_destroy

    resources :locations
    get 'locations/:id/delete' => 'locations#delete', :as => :location_delete
    get 'locations/:id/destroy' => 'locations#destroy', :as => :location_destroy

    resources :projects
    get 'projects/:id/delete' => 'projects#delete', :as => :project_delete
    get 'projects/:id/destroy' => 'projects#destroy', :as => :project_destroy

    resources :perso_projects
    get 'perso_projects/:id/delete' => 'perso_projects#delete', :as => :perso_project_delete
    get 'perso_projects/:id/destroy' => 'perso_projects#destroy', :as => :perso_project_destroy

    resources :photo
    get 'photo/:id/delete' => 'photo#delete', :as => :photo_delete
    get 'photo/:id/destroy' => 'photo#destroy', :as => :photo_destroy

    resources :albums
    get 'albums/:id/delete' => 'albums#delete', :as => :album_delete
    get 'albums/:id/destroy' => 'albums#destroy', :as => :album_destroy

    get 'contact/index' => 'contact#index', :as => :contact
    get 'contact/update' => 'contact#update', :as => :update_contact

  end

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

end

app/views/shared/_adminnav.html.erb
<div class="admin_nav small-12 small-centered columns" data-no-turbolink>
  <%= image_tag "admin/logo.png", :class => 'admin_logo no-border' %>

  <%= link_to t('admin.layout.nav.about'), controller: "about", action: "show" %>
  <%= link_to t('admin.layout.nav.book'), controller: "locations", action: "index" %>
  <%= link_to t('admin.layout.nav.resume'), controller: "resume", action: "index" %>
  <%= link_to t("admin.layout.nav.perso"), admin_perso_projects_path %>
  <%= link_to t('admin.layout.nav.albums'), controller: "albums", action: "index" %>
  <%= link_to t('admin.layout.nav.contact'), admin_contact_path %>

  <div class="nav-right">
    <a href="#" class="button tiny radius" data-dropdown="drop"><%=t('admin.language.lang')%> &raquo;</a>
    <ul id="drop" class=" tiny f-dropdown" data-dropdown-content>
    <li><%= link_to t('admin.language.fr'), change_locale_path(:fr) %></li>
    <li><%= link_to t('admin.language.en'), change_locale_path(:en) %></li>
    </ul>

    <%= link_to t('admin.layout.session.logout'), destroy_user_session_path, method: :delete %>
  </div>
</div>

app/views/shared/_appnav.html.erb
<div class="app_nav small-12 small-centered columns" data-no-turbolink>
  <%= link_to image_tag("admin/logo.png", :class => 'app_logo no-border'), root_path %>

  <%= link_to t('app.layout.nav.about'), about_path %>
  <%= link_to t('app.layout.nav.book'), book_path %>
  <%= link_to t('app.layout.nav.resume'), resume_path %>
  <%= link_to t('app.layout.nav.perso'), perso_projects_path %>
  <%= link_to t('app.layout.nav.photos'), photos_path %>
  <%= link_to t('app.layout.nav.contact'), contacts_path %>

  <div class="nav-right">
    <%= link_to image_tag('flags/french.png', :alt => t('admin.language.fr'), :class => 'lang_thumb'), change_locale_path(:fr) %>
    <%= link_to image_tag('flags/english.png', :alt => t('admin.language.en'), :class => 'lang_thumb'), change_locale_path(:en) %>
  </div>

  <div class="page-title small-5">
    <span><%= @page_title %></span>
    <% if params[:controller] == 'resume' %>
          <% if @lang == :fr && File.exist?( Rails.root + "public/files/CV - Audrey LEPERS-TASSY.pdf")%> <!-- location language handling -->
              <%= link_to image_tag("download/download.png", :class => "download-icon" ), '/files/CV - Audrey LEPERS-TASSY.pdf', { target: '_blank', :class => "download-link" } %>
          <% elsif @lang == :en && File.exist?( Rails.root + "public/files/resume - Audrey LEPERS-TASSY.pdf") %>
              <%= link_to image_tag("download/download.png", :class => "download-icon" ), '/files/resume - Audrey LEPERS-TASSY.pdf', { target: '_blank', :class => "download-link" } %>
          <% end %>
    <% end %>
  </div>
</div>