config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  devise_for :users, path_names: {
                 sign_in: 'login',
                 sign_out: 'logout',
                   }

  get 'about/index', to: 'about#index', as: :about

  get 'photos/index', to: 'photos#index', as: :photos
  get 'photos/show', to: 'photos#show', as: :album

  get 'perso/index', to: 'perso#index', as: :perso_projects
  get 'perso/show', to: 'perso#show', as: :perso_project

  get 'resume/index', to: 'resume#index', as: :resume

  get 'book/index', to: 'book#index', as: :book

  get 'locations/show', to: 'locations#show', as: :location

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  get 'projects/show'

  namespace :admin do
    get '', to: 'about#show', as: '/'

    match '/about/:id/edit' => 'about#update', :via => :post
    resources :about

    resources :resume
    post 'resume/resume_upload' => 'resume#resume_upload', :as => :resume_upload

    resources :cursus
    get 'cursus/:id/delete' => 'cursus#delete', :as => :cursu_delete
    get 'cursus/:id/destroy' => 'cursus#destroy', :as => :cursu_destroy

    resources :experience
    get 'experience/:id/delete' => 'experience#delete', :as => :experience_delete
    get 'experience/:id/destroy' => 'experience#destroy', :as => :experience_destroy

    resources :skills
    get 'skills/:id/delete' => 'skills#delete', :as => :skill_delete
    get 'skills/:id/destroy' => 'skills#destroy', :as => :skill_destroy

    resources :locations
    get 'locations/:id/delete' => 'locations#delete', :as => :location_delete
    get 'locations/:id/destroy' => 'locations#destroy', :as => :location_destroy

    resources :projects
    get 'projects/:id/delete' => 'projects#delete', :as => :project_delete
    get 'projects/:id/destroy' => 'projects#destroy', :as => :project_destroy

    resources :perso_projects
    get 'perso_projects/:id/delete' => 'perso_projects#delete', :as => :perso_project_delete
    get 'perso_projects/:id/destroy' => 'perso_projects#destroy', :as => :perso_project_destroy

    resources :photo
    get 'photo/:id/delete' => 'photo#delete', :as => :photo_delete
    get 'photo/:id/destroy' => 'photo#destroy', :as => :photo_destroy

    resources :albums
    get 'albums/:id/delete' => 'albums#delete', :as => :album_delete
    get 'albums/:id/destroy' => 'albums#destroy', :as => :album_destroy

    get 'contact/index' => 'contact#index', :as => :contact
    get 'contact/update' => 'contact#update', :as => :update_contact

  end

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController

  layout 'admin'
  before_action :authenticate_user!

  def index
    if I18n.locale == "fr"
      @projects = Album.all.where("project = ?",true).order(name_fr: :desc)
    else
      @projects = Album.all.where("project = ?",true).order(name_en: :desc)
    end
  end

  def show
    @project = Album.find(params[:id])
    @photos = @project.photos
  end

  def new
    @project = Album.new
    @location_id = params[:location_id]
  end

  def create

    @project = Album.new(project_params)
    if @project.save
      flash[:notice] = "Le projet à été créé"
      redirect_to(admin_project_path(:id => @project.id))
    else
      render('new')
    end
  end

  def edit
    @project = Album.find(params[:id])
    @photos = @project.photos
  end

  def update
    @project = Album.find(params[:id])
    if @project.update_attributes(project_params)
      flash[:notice] = "Le projet est mis à jour"
      redirect_to(admin_project_path(:id => @project.id))
    else
      flash[:error] = "Une erreur est survenue lors de la mise a jour."
      redirect_to(edit_admin_project_path(:id => @project.id))
    end
  end

  def delete
    @project = Album.find(params[:id])
    @photos = @project.photos
  end

  def destroy
    @project = Album.find(params[:id])
    @location_id = @project.location_id
    @project.destroy
    flash[:notice] = "Le projet à été supprimé"
    redirect_to(:controller => 'locations', :action => 'edit', :id => @location_id)
  end

  private

  def project_params
    params.require(:album).permit(:name_fr, :name_en, :main_image, :description_fr, :description_en, :location_id, :project, :perso)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
    @project = Album.find(params[:id])
    @photos = @project.photos

    if I18n.locale == :fr
      @page_title = @project.name_fr
      @description = @project.description_fr
    else
      @page_title = @project.name_en
      @description = @project.description_en
    end
  end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/projects/create.html.erb
<h1>Admin::Projects#create</h1>
<p>Find me in app/views/admin/projects/create.html.erb</p>

app/views/admin/projects/delete.html.erb
<h1><%=t('admin.projects.delete.title')%></h1>

<%= link_to t('admin.buttons.delete'), admin_project_destroy_path(:id => @project.id), :class => 'button radius tiny alert' %>
<%= link_to t('admin.buttons.edit'), edit_admin_project_path(@project), :class => 'button radius tiny secondary' %>
<%= link_to t('admin.buttons.back'), edit_admin_location_path(:id => @project.location_id), :class => 'button radius tiny' %>

<div class="row">

  <div class="infos small-9 columns">
    <ul class="tabs" data-tab>
      <li class="tab-title active"><a href="#panel1"><%=t('admin.language.fr')%></a></li>
      <li class="tab-title"><a href="#panel2"><%=t('admin.language.en')%></a></li>
    </ul>

    <div class="tabs-content">

      <div class="content contained active" id="panel1">

        <table>
          <tr>
            <td class="cell1"><strong><%=t('activerecord.attributes.albums.name_fr')%>:</strong></td>
            <td class="cell2"><%= @project.name_fr %></td>
          </tr>
          <tr>
            <td colspan="2">
              <div class="separator small-12 columns">
                <div class="mask-small"></div>
              </div>
            </td>
          </tr>
          <tr>
            <td class="cell1"><strong><%=t('activerecord.attributes.albums.description_fr')%>:</strong></td>
            <td class="cell2"><%= @project.description_fr %></td>
          </tr>
        </table>

      </div>

      <div class="content contained" id="panel2">

        <table>
          <tr>
            <td class="cell1"><strong><%=t('activerecord.attributes.albums.name_en')%>:</strong></td>
            <td class="cell2"><%= @project.name_en %></td>
          </tr>
          <tr>
            <td colspan="2">
              <div class="separator small-12 columns">
                <div class="mask-small"></div>
              </div>
            </td>
          </tr>
          <tr>
            <td class="cell1"><strong><%=t('activerecord.attributes.albums.description_en')%>:</strong></td>
            <td class="cell2"><%= @project.description_en %></td>
          </tr>
        </table>

      </div>

    </div>
  </div>

  <div class="info-image small-3 columns">
    <%= image_tag @project.main_image(:medium) %>
  </div>

</div>

<div class="row">
  <div class="small-12 small-centered">
    <div class="picture-gallery inline">
      <% @photos.each do |p|%>
          <div class="picture" image-id="<%= p.id %>">
            <span class="delete-image"><%= image_tag 'delete/delete.png', :class => "no-border" %></span>
            <%=image_tag(p.image(:thumb))%>
          </div>
      <% end %>
    </div>
  </div>
</div>


<%= link_to t('admin.buttons.delete'), admin_project_destroy_path(:id => @project.id), :class => 'button radius tiny alert' %>
<%= link_to t('admin.buttons.edit'), edit_admin_project_path(@project), :class => 'button radius tiny secondary' %>
<%= link_to t('admin.buttons.back'), edit_admin_location_path(:id => @project.location_id), :class => 'button radius tiny' %>

app/views/admin/projects/destroy.html.erb
<h1>Admin::Projects#destroy</h1>
<p>Find me in app/views/admin/projects/destroy.html.erb</p>

app/views/admin/projects/edit.html.erb
<h1><%=t('admin.projects.edit.title')%></h1>

<% if @project.errors.any? %>
    <div class="error_explanation small-8 small-centered columns">
      <h6><%= @project.errors.count %> <%=t('admin.forms.message.error')%> :</h6>

      <ul>
        <% @project.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_for(@project, url: admin_project_path) do |f| %>

    <div class="row">

      <div class="infos small-9 columns">
        <ul class="tabs" data-tab>
          <li class="tab-title active"><a href="#panel1"><%=t('admin.language.fr')%></a></li>
          <li class="tab-title"><a href="#panel2"><%=t('admin.language.en')%></a></li>
        </ul>

        <div class="tabs-content">

          <div class="content contained active" id="panel1">

            <table>
              <tr><td class="cell1"><%= f.label t('activerecord.attributes.albums.name_fr')%></td>
                <td class="cell2"><%= f.text_field :name_fr %></td>
              </tr>
              <tr>
                <td colspan="2">
                  <div class="separator small-12 columns">
                    <div class="mask-small"></div>
                  </div>
                </td>
              </tr>
              <tr>
                <td class="cell1"><%= f.label t('activerecord.attributes.albums.description_fr')%></td>
                <td class="cell2"><%= f.text_area :description_fr, :class => 'ckeditor' %></td>
              </tr>
            </table>

          </div>

          <div class="content contained" id="panel2">

            <table>
              <tr>
                <td class="cell1"><%= f.label t('activerecord.attributes.albums.name_en')%></td>
                <td class="cell2"><%= f.text_field :name_en%></td>
              </tr>
              <tr>
                <td colspan="2">
                  <div class="separator small-12 columns">
                    <div class="mask-small"></div>
                  </div>
                </td>
              </tr>
              <tr>
                <td class="cell1"><%= f.label t('activerecord.attributes.albums.description_en')%></td>
                <td class="cell2"><%= f.text_area :description_en, :class => 'ckeditor' %></td>
              </tr>
            </table>

          </div>

        </div>
      </div>

      <div class="info-image small-3 columns">
        <%= f.label t('activerecord.attributes.albums.main_image')%>
        <%= f.file_field :main_image %>
      </div>

    </div>

    <div class="row">
      <div class="small-12 small-centered">
        <div class="picture-gallery inline">
          <% @photos.each do |p|%>
              <div class="picture" image-id="<%= p.id %>">
                <span class="delete-image"><%= image_tag 'delete/delete.png', :class => "no-border" %></span>
                <%=image_tag(p.album_image(:thumb))%>
              </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="submit">
      <%= f.submit t('admin.buttons.save'), :class => 'button radius tiny info' %>
    </div>
<% end %>

app/views/admin/projects/index.html.erb
<h1>Admin::Projects#index</h1>
<p>Find me in app/views/admin/projects/index.html.erb</p>

app/views/admin/projects/new.html.erb
<h1><%=t('admin.projects.new.title')%></h1>

<% if @project.errors.any? %>
    <div class="error_explanation small-8 small-centered columns">
      <h6><%= @project.errors.count %> <%=t('admin.forms.message.error')%> :</h6>

      <ul>
        <% @project.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_for(@project, url: admin_projects_path) do |f| %>

    <div class="row">

      <div class="infos small-9 columns">
        <ul class="tabs" data-tab>
          <li class="tab-title active"><a href="#panel1"><%=t('admin.language.fr')%></a></li>
          <li class="tab-title"><a href="#panel2"><%=t('admin.language.en')%></a></li>
        </ul>

        <div class="tabs-content">

          <div class="content contained active" id="panel1">

            <table>
              <tr><td class="cell1"><%= f.label t('activerecord.attributes.albums.name_fr')%></td>
                <td class="cell2"><%= f.text_field :name_fr %></td>
              </tr>
              <tr>
                <td colspan="2">
                  <div class="separator small-12 columns">
                    <div class="mask-small"></div>
                  </div>
                </td>
              </tr>
              <tr>
                <td class="cell1"><%= f.label t('activerecord.attributes.albums.description_fr')%></td>
                <td class="cell2"><%= f.text_area :description_fr, :class => 'ckeditor' %></td>
              </tr>
            </table>

          </div>

          <div class="content contained" id="panel2">

            <table>
              <tr>
                <td class="cell1"><%= f.label t('activerecord.attributes.albums.name_en')%></td>
                <td class="cell2"><%= f.text_field :name_en%></td>
              </tr>
              <tr>
                <td colspan="2">
                  <div class="separator small-12 columns">
                    <div class="mask-small"></div>
                  </div>
                </td>
              </tr>
              <tr>
                <td class="cell1"><%= f.label t('activerecord.attributes.albums.description_en')%></td>
                <td class="cell2"><%= f.text_area :description_en, :class => 'ckeditor' %></td>
              </tr>
            </table>

          </div>

        </div>
      </div>

      <div class="info-image small-3 columns">
        <%= f.label t('activerecord.attributes.albums.main_image')%>
        <%= f.file_field :main_image %>
      </div>

    </div>

    <div>
      <%= f.hidden_field :location_id, :value => @location_id %>
    </div>

    <div>
      <%= f.hidden_field :project, :value => 1 %>
    </div>

    <div class="submit">
      <%= f.submit t('admin.buttons.save'), :class => 'button radius tiny info' %>
    </div>
<% end %>

app/views/admin/projects/show.html.erb
<h1><%=t('admin.projects.show.title')%></h1>

<%= link_to t('admin.buttons.edit'), edit_admin_project_path(@project), :class => 'button radius tiny secondary' %>
<%= link_to t('admin.buttons.back'), edit_admin_location_path(:id => @project.location_id), :class => 'button radius tiny ' %>
<%= link_to t('admin.buttons.add_photo'), new_admin_photo_path(:album_id => @project.id, :project => 1), :class => 'button radius tiny success' %>

<div class="row">

  <div class="infos small-9 columns">
    <ul class="tabs" data-tab>
      <li class="tab-title active"><a href="#panel1"><%=t('admin.language.fr')%></a></li>
      <li class="tab-title"><a href="#panel2"><%=t('admin.language.en')%></a></li>
    </ul>

    <div class="tabs-content">

      <div class="content contained active" id="panel1">

        <table>
          <tr>
            <td class="cell1"><strong><%=t('activerecord.attributes.albums.name_fr')%>:</strong></td>
            <td class="cell2"><%= @project.name_fr.html_safe %></td>
          </tr>
          <tr>
            <td colspan="2">
              <div class="separator small-12 columns">
                <div class="mask-small"></div>
              </div>
            </td>
          </tr>
          <tr>
            <td class="cell1"><strong><%=t('activerecord.attributes.albums.description_fr')%>:</strong></td>
            <td class="cell2"><%= @project.description_fr.html_safe %></td>
          </tr>
        </table>

      </div>

      <div class="content contained" id="panel2">

        <table>
          <tr>
            <td class="cell1"><strong><%=t('activerecord.attributes.albums.name_en')%>:</strong></td>
            <td class="cell2"><%= @project.name_en.html_safe %></td>
          </tr>
          <tr>
            <td colspan="2">
              <div class="separator small-12 columns">
                <div class="mask-small"></div>
              </div>
            </td>
          </tr>
          <tr>
            <td class="cell1"><strong><%=t('activerecord.attributes.albums.description_en')%>:</strong></td>
            <td class="cell2"><%= @project.description_en.html_safe %></td>
          </tr>
        </table>

      </div>

    </div>
  </div>

  <div class="info-image small-3 columns">
    <%= image_tag @project.main_image(:medium) %>
  </div>

</div>

<div class="row">
  <div class="small-12 small-centered">
    <div class="picture-gallery inline">
      <% @photos.each do |p|%>
          <div class="picture">
            <%=image_tag(p.album_image(:thumb))%>
          </div>
      <% end %>
    </div>
  </div>
</div>

<%= link_to t('admin.buttons.edit'), edit_admin_project_path(@project), :class => 'button radius tiny secondary' %>
<%= link_to t('admin.buttons.back'), edit_admin_location_path(:id => @project.location_id), :class => 'button radius tiny ' %>
<%= link_to t('admin.buttons.add_photo'), new_admin_photo_path(:album_id => @project.id, :project => 1), :class => 'button radius tiny success' %>

app/views/admin/projects/update.html.erb
<h1>Admin::Projects#update</h1>
<p>Find me in app/views/admin/projects/update.html.erb</p>